services:
  - type: web
    name: rain_project
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn rain_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rain_project.settings
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    region: oregon